### ISSUE TITLE
User can create a handle to identify themselves.

### ISSUE THREAD

**Issue by mstrieleman** [mstrieleman/lex#1]
# Motivation
A user needs to create a unique identifier to send and receive messages associated with their handle.

# Implementation 
1. User opens app
2. User is presented with a text input for choosing a handle
3. User submits handle to App
4. App sends the handle to the server
5. Server checks handle against the database 
- If the handle is taken respond with an error 
- if the handle is available proceed
6. Server inserts username into the database
7. The server returns username to the app with 'creation success'
8. App shows username creation success to user

# Wireframe
![screen shot 2018-04-26 at 2 29 46 pm](https://user-images.githubusercontent.com/14259747/39333073-6398bcf6-495e-11e8-8e8e-fb9d7df8172a.png)
![screen shot 2018-04-26 at 2 29 55 pm](https://user-images.githubusercontent.com/14259747/39333083-6715272a-495e-11e8-9081-09ea80d70fb7.png)
*Logo not inserted yet

# Research
[Expo - Emulator / React Native](https://expo.io/)
[React Native Docs](https://facebook.github.io/react-native/)
Mobile app to server communication

# Tasks
- [x] Create a wireframe for choosing a handle text input, button, logo,
- [x] Create a wireframe for username creation success
- [x] Create a wireframe for username creation fail

# Client
- [x] Get bare-bones app running in expo/emulator 
- [x] Create a form for the user to submit a username
- [x] Define a function for posting usernames to server
- [x] Register post function to fire upon button press 
- [x] Create a view for showing the user that username is unavailable
- [x] Create a view for showing the user that username creation was a success

# Server
- [x] Create server route for handling post requests of usernames
- [x] Create check to see if the username is already been created in the database
- [x] If the username is already taken, respond to the user with an error
- [x] If the username is available, insert username to database
- [x] Have server respond to the client that user creation was a success
