### ISSUE TITLE
A user can send a message in a global chat  room.

### ISSUE THREAD

**Issue by mstrieleman** [mstrieleman/lex#13]
# Motivation
After a user joins a general room the user can type a message to other users in the room

# Implementation 
1. After a user logs in with their handle; they are presented with a text box, send button, and an area for chat messages to show up
2. The user types a message into the chat box
3. The user clicks send
4. The client sends the chat message via socket.io emit to the server
5. The server stores the emitted message and emits that message to the global room
6. The client receives the updated messages from the server and displays them in the chat area

# Flow Chart
![flowchart](https://user-images.githubusercontent.com/14259747/42569868-defbd056-84c6-11e8-85fe-dae0c451b396.PNG)

# Wireframe
![wireframe](https://user-images.githubusercontent.com/14259747/42569877-e31cb4de-84c6-11e8-91a2-796eb8dfcb47.PNG)

# Research
[Socket.io](https://socket.io/)
[React Native](https://facebook.github.io/react-native/)

# Tasks
**Server**
- [x]  Enable the server to listen for messages emitted to the global room
- [x]  Create a storage for messages to be stored on the server once they are emitted from the client
- [x]  Emit the stored messages to all users in the global room

**Client**
- [x]  Create a text box for the user to input their messages
- [x]  Create a button that allows for submitting user input
- [x]  Store the user message in state
- [x]  Create a request to the server with the message stored in state
- [x]  Allow the client to listen for emitted messages from the server
- [x]  Once a message has been emitted by the server update the state of received messages
- [x]  Display received messages area with the newly emitted text
- [x]  Style

## Screen capture
![screencapture](https://user-images.githubusercontent.com/14259747/42579654-a59a6ed2-84dd-11e8-8aa6-d7ddb64091c8.gif)
