### ISSUE TITLE
User can join a general room

### ISSUE THREAD

**Issue by mstrieleman** [mstrieleman/lex#2]
# Motivation
A user has the ability to join a lobby room after selecting a handle, the room will display all users currently in the channel and any new connections/disconnects.

# Implementation 
1. After the user chooses a handle 
2. Client requests socket from the server
3. Server establishes a connection with the client
4. Client sends current user handle to the server
5. Server adds user handle to the online user list 
6. Server sends online user list to the client
7. Server joins the client to lobby room
8. Server notifies clients of new user connections 
9. Server notifies clients of new user disconnections 

# Flow Chart
![screen shot 2018-05-01 at 3 16 16 pm](https://user-images.githubusercontent.com/14259747/39496301-a3c0bab6-4d52-11e8-82e3-faf033ac224f.png)
![screen shot 2018-05-01 at 3 17 04 pm](https://user-images.githubusercontent.com/14259747/39496320-bb370bc8-4d52-11e8-900a-1a999cfdf613.png)
![screen shot 2018-05-01 at 3 23 08 pm](https://user-images.githubusercontent.com/14259747/39496508-9a40aa7c-4d53-11e8-9f3e-5cdabccfb963.png)

# Wireframe
![screen shot 2018-05-01 at 3 18 46 pm](https://user-images.githubusercontent.com/14259747/39496381-fa2a84ea-4d52-11e8-99cd-61b84f7d1bf0.png)

# Research
[Socket.io](https://socket.io/docs/)
[React native docs](https://facebook.github.io/react-native/docs/getting-started.html)

# Tasks
**General** 
- [x] Create a flow chart documenting the flow of the app
- [x] Create a wireframe for the client UI

**Server**
- [x] Initialize Socket.io to listen for socket requests
- [x] Accept and open incoming socket requests
- [x] Define a function that gets incoming users handle and stores it in an array
- [x] Define a function that returns online user list to the client 
- [x] Join the incoming user connection the lobby room
- [x] Have the server notify with new connections and disconnections

**Client**
- [x] Direct user to lobby screen
- [x] Have client request socket from server
- [x] Define a function that sends users handle to the server 
- [x] Define a function that displays online user list sent from the server
- [x] Define a function that updates online user list every time it changes
