### ISSUE TITLE
Revise style sheets within app to use single style sheet instead of multiple.

### ISSUE THREAD

**Issue by mstrieleman** [mstrieleman/lex#25]
## **Issue Intent**
Remove styling from individual screens and revise them to use a single stylesheet located outside of a screen. 

This will eventually segue into breaking up components into actual components.

## Flowchart
![lc revision - styles 1](https://user-images.githubusercontent.com/14259747/43651884-78b474f8-96f8-11e8-8f76-b3c7c4f8a244.PNG)
![lc revision - styles 2](https://user-images.githubusercontent.com/14259747/43651894-7d787b38-96f8-11e8-8689-2c754b23cb2b.PNG)
![lc revision - styles 3](https://user-images.githubusercontent.com/14259747/43651900-7f5dced0-96f8-11e8-8ae1-d40db4d3bf32.PNG)

## Research
[Socket.io](https://socket.io/)
[React Native](https://facebook.github.io/react-native/)
[React Native Style Cheat Sheet](https://github.com/vhpoet/react-native-styling-cheat-sheet)

## **Tasks**
**client**
- [x] Create a new style sheet
- [x] Create common styles within our new style sheet that are widely used throughout the app
- [x] Identify and rename all container styles
- [x] Identify and rename all buttons styles
- [x] Identify and rename all text styles 
- [x] Identify and remove any inline styles that are not critical 
- [x] Revise and consolidate the style sheet within the home screen
- [x] Revise and consolidate the style sheet within the inbox screen
- [x] Revise and consolidate the style sheet within the lobby screen
- [x] Revise and consolidate the style sheet within the users screen
- [x] Populate new stylesheet with common styles 
- [x] Remove all prior styles defined within their screens
- [x] Import new style sheet into appropriate screens
- [x] Touchups
