### ISSUE TITLE
User can add other users to a friends list.

### ISSUE THREAD

**Issue by mstrieleman** [mstrieleman/lex#4]
# Motivation
Upon choosing a handle and logging in, the user will be able to navigate to an area within the app that will allow them to add other users who are currently online to a friends list.

# Implementation 
1. After the user logs in with their chosen handle they will be navigated to the "lobby" screen.
2. The user can then go to the "users" screen and they will be presented with an area that displays current users who are online; and a separate section for adding someone to your friend's list.
3. The user will have the ability to type in a text box and push an "Add" button once they have entered in the desired handle to be added.
4. Upon pressing the add button the client will check to make sure that the user exists and display a notification on if the submission to the friend's list was accepted or not. 
5.  Once a handle has been successfully added to the user's friend list he or she will have that users name displayed in the lower half of the screen in the friend's list area.

# Flow Chart
_Click for a better view._
**Client**
![flowchart feature four](https://user-images.githubusercontent.com/14259747/42958754-59c9d736-8b3b-11e8-8eca-c2745a0488cd.PNG)
**Server**
![flowchart feature four server](https://user-images.githubusercontent.com/14259747/42959643-63e5c6dc-8b3e-11e8-8aad-0077055caea1.PNG)

# Wireframe
**New lobby screen layout**
![wireframe feature four 1](https://user-images.githubusercontent.com/14259747/42958773-64c47e66-8b3b-11e8-9710-7c003b51bd8f.PNG)
**Users screen**
![wire frame feature 4 1](https://user-images.githubusercontent.com/14259747/42958775-66a077da-8b3b-11e8-8aaa-45c4373484ec.PNG)
_Layouts still subject to change and revision._

# Research
[Socket.io](https://socket.io/)
[React Native](https://facebook.github.io/react-native/)

# Tasks
**Server**
- [x]  Create a socket that is activated by the client submitting a handle to be added.
- [x]  Have the server verify if the handle exists within the online user's list.
- [x]  Once the handle has been verified; respond to the client with the go-ahead to add the handle to the user's friend list.
- [x]  If the handle cannot be verified; respond to the client letting it know that no such user exists.

**Client**
- [x]  Create a variable within state that will hold our friend's list handles.
- [x]  Create a new screen that will be dedicated to the displaying of users that are online; and the user's friends list.
- [x]  Create a button within the lobby screen that will navigate to the new screen we just created.
- [x]  Upon clicking the button that will handle our navigation; add a function that will fire to pass along the current clients handle to the new screen.
- [x]  Using the data we created in feature #2; create a flat list that will display all of our current online users in the top half section of our user's screen.
- [x]  In the lower portion of the screen; create a text input and a button that can be used by the user to input and submit handles they wish to add to their friend's list.
- [x]  Have our new button trigger a function that will grab the text in the input field and store it in state.
- [x]  Create a new socket within the input function that will emit the input text to the server.
- [x]  Take the response from the server and create an if/else statement that will alert the user according to the response of the server (Failed or Success).
- [x]  Display the server's response on the user's screen, near the friend's list area.
- [x]  Once the server gives the go-ahead to add the users handle to the friend's list; display the users handle within the friend's list section of the screen using a flat list.
- [ ]  Style Accordingly

## Screen capture
![ezgif com-optimize](https://user-images.githubusercontent.com/14259747/42960858-efdd06c0-8b41-11e8-9a3f-17fa8844ad6a.gif)
