### ISSUE TITLE
User can block other users.

### ISSUE THREAD

**Issue by mstrieleman** [mstrieleman/lex#5]
## **Issue Intent**
A user shouldn't be forced to listen or talk to anyone they don't want to talk to, therefore a user should be able to add another user to a list that prevents all communication from that user.

## **Implementation**
1. A user is annoyed by another user
2. A user navigates to the users screen
3. A user clicks the BLOCK button (which will later be substituted for a block icon)
4. The client renders a modal which slides in from the bottom of the screen
5. The user is presented with a screen that looks similar to the normal users screen for adding friends but with a few differences: 
6. The BLOCK button is now replaced with a CLOSE button which will close the modal
7. The ADD button is replaced with a BLK button
8. The friend's list now displays a blocked list
9. The user can enter a handle into the text input field and click the BLK button
10. The client will send the server the handle of whoever was entered into the text field
11. The server will take the handle and populate a blocked users array and return the handle of the user blocked
12. The client will take the returned handle and add it to the blocked users list
13. The server will now check the blocked users list before sending any message (private or public)
14. If the user is on the clients blocked user list the server will omit the message rather than sending it to the client

## **Flow Chart**
_Click for a much larger & better view of the flow chart_
![ft6 block user flow](https://user-images.githubusercontent.com/14259747/43302259-5c1a1a94-911e-11e8-9320-70e6b1f664a3.PNG)

## **Wireframe**
![ft6 wireframe 1](https://user-images.githubusercontent.com/14259747/43302271-63b44b58-911e-11e8-94e2-174dcff6139d.PNG)

![ft6 wireframe 2](https://user-images.githubusercontent.com/14259747/43302273-674170f2-911e-11e8-9712-e7aba38b0ed8.PNG)

![ft6 wireframe 3](https://user-images.githubusercontent.com/14259747/43302276-694b42ba-911e-11e8-8af4-b41f765e42bd.PNG)

## Research
[Socket.io](https://socket.io/)
[React Native](https://facebook.github.io/react-native/)

## **Tasks**
**client**
- [x]  Create a BLOCK button on the users page that will toggle a modal upon click
- [x]  Create a modal within the users screen and populate it with a similar layout to the users screen
- [x]  In the new modal change the BLOCK button into a CLOSE button that triggers the closing of the modal
- [x]  Add an online users area with a list that shows the current online users
- [x]  Add a blocked users area 
- [x]  Create a list that will populate on adding a new blocked user
- [x]  Create a text input and button that are tied together that can submit blocked users to the server
- [x]  Create a check that notifies the user when they have successfully added someone to the blocked users list 
- [x]  Have the client list for the server responding with successful additions to the user blocked list
- [x]  Upon successfully adding someone to the blocked user list on the server: take the user handle given by the server and store it in state to be used in our displayed blocked user list.
- [x]  Style accordingly

**server**
- [x] Have the server listen for the client emitting a user to be added to the blocked user list
- [x] Upon retrieving a user to be blocked, add it to a blocked user list array
- [x] Return the handle of the user to be blocked by the client
- [x] Before sending any private message, iterate through the blocked users list beforehand and if the user sending the message matches an entry in the clients blocked list then omit the message
- [x] Before sending and public message, iterate through the block users list beforehand and if the user sending the message matches an entry in the clients blocked list then omit the message 

## **Completed Screencap**
![ft6 block users](https://user-images.githubusercontent.com/14259747/43464361-c97955a4-948f-11e8-8833-f2c5a8bbbf11.gif)
